// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnucqIj_CX7Wr0bpZQE6KUvUarFK7VlS8',
    appId: '1:787212958078:web:3fbe08aaba64b81b7d5b2f',
    messagingSenderId: '787212958078',
    projectId: 'tic-tac-toe-super-strike-a5f38',
    authDomain: 'tic-tac-toe-super-strike-a5f38.firebaseapp.com',
    databaseURL: 'https://tic-tac-toe-super-strike-a5f38-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-super-strike-a5f38.appspot.com',
    measurementId: 'G-6YM89C98SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmwNGFgDs99v9LCynIaCHEq0_35cFHwwo',
    appId: '1:787212958078:android:79215dcc9b4ebdcd7d5b2f',
    messagingSenderId: '787212958078',
    projectId: 'tic-tac-toe-super-strike-a5f38',
    databaseURL: 'https://tic-tac-toe-super-strike-a5f38-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-super-strike-a5f38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkLqYlqg0srnY0_QKKwoLMAiSe3yDnN1E',
    appId: '1:787212958078:ios:a51f19b5d3bc7e337d5b2f',
    messagingSenderId: '787212958078',
    projectId: 'tic-tac-toe-super-strike-a5f38',
    databaseURL: 'https://tic-tac-toe-super-strike-a5f38-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-super-strike-a5f38.appspot.com',
    iosClientId: '787212958078-kv47f5iu422utrcnk6vf2tob72v7gcs0.apps.googleusercontent.com',
    iosBundleId: 'com.fuzzlegames.tictactoesuperstrike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkLqYlqg0srnY0_QKKwoLMAiSe3yDnN1E',
    appId: '1:787212958078:ios:a51f19b5d3bc7e337d5b2f',
    messagingSenderId: '787212958078',
    projectId: 'tic-tac-toe-super-strike-a5f38',
    databaseURL: 'https://tic-tac-toe-super-strike-a5f38-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tic-tac-toe-super-strike-a5f38.appspot.com',
    iosClientId: '787212958078-kv47f5iu422utrcnk6vf2tob72v7gcs0.apps.googleusercontent.com',
    iosBundleId: 'com.fuzzlegames.tictactoesuperstrike',
  );
}
